In [12]:
import pandas as pd

In [13]:
sql = pd.read_csv(r"E:\FSDS\Dataset\vehicle_coupon.csv")

In [14]:
sql.head()

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5

In [15]:
sql[['weather','temperature']]

      weather  temperature
0       Sunny           55
1       Sunny           80
2       Sunny           80
3       Sunny           80
4       Sunny           80
...       ...          ...
12679   Rainy           55
12680   Rainy           55
12681   Snowy           30
12682   Snowy           30
12683   Sunny           80

[12684 rows x 2 columns]

In [16]:
sql.head(10)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
5,No Urgent Place,Friend(s),Sunny,80,6PM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,6
6,No Urgent Place,Friend(s),Sunny,55,2PM,Carry out & Take away,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,7
7,No Urgent Place,Kid(s),Sunny,80,10AM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,8
8,No Urgent Place,Kid(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,9
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10

In [17]:
sql['passanger'].unique() # unique parameter information

array(['Alone', 'Friend(s)', 'Kid(s)', 'Partner'], dtype=object)

In [18]:
sql['passanger'].nunique() #give sum of unique attributes

4

In [31]:
sql[sql['Destination']=='Home']

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
13,Home,Alone,Sunny,55,6PM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,1,0,1,14
14,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,15
15,Home,Alone,Sunny,80,6PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,16
35,Home,Alone,Sunny,55,6PM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,1,0,1,36
36,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Male,21,Single,...,4~8,4~8,less1,1,1,0,0,1,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12675,Home,Alone,Snowy,30,10PM,Coffee House,2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12676
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680

In [33]:
sql[sql['Destination']=='No Urgent Place'] #This line gives how many people's destination is no urgent place

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12667,No Urgent Place,Alone,Rainy,55,10AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12668
12668,No Urgent Place,Alone,Sunny,80,10AM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12669
12669,No Urgent Place,Partner,Sunny,30,10AM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12670
12670,No Urgent Place,Partner,Rainy,55,6PM,Bar,2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12671
12671,No Urgent Place,Partner,Snowy,30,10AM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12672

In [21]:
sql.sort_values('coupon')

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
11702,Home,Partner,Sunny,30,10PM,Bar,2h,Female,50plus,Married partner,...,4~8,1~3,less1,1,1,1,0,1,0,11703
9930,No Urgent Place,Alone,Snowy,30,2PM,Bar,1d,Female,21,Single,...,gt8,gt8,4~8,1,0,0,0,1,0,9931
10632,Home,Alone,Rainy,55,6PM,Bar,1d,Male,21,Single,...,gt8,less1,less1,1,1,1,0,1,0,10633
7997,No Urgent Place,Friend(s),Rainy,55,10PM,Bar,2h,Male,26,Unmarried partner,...,4~8,never,1~3,1,1,0,0,1,1,7998
11166,Work,Alone,Snowy,30,7AM,Bar,1d,Female,41,Married partner,...,gt8,1~3,less1,1,1,1,0,1,0,11167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,Home,Alone,Sunny,80,6PM,Restaurant(<20),1d,Female,31,Unmarried partner,...,1~3,1~3,less1,1,0,0,1,0,1,10477
5447,Home,Alone,Sunny,80,10PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,0,0,1,0,0,5448
10478,Home,Alone,Snowy,30,10PM,Restaurant(<20),2h,Female,31,Unmarried partner,...,1~3,1~3,less1,1,1,1,0,1,0,10479
5440,No Urgent Place,Alone,Sunny,80,2PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,1,0,0,1,0,5441
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

df.sort_values() is the method used for sorting 

'coupon' is the name of the column you want to sort by

ascending = False is the key part . By default , sort_values sorts in ascending order 
(ascending=True) to get a descending sort,you must explicitly set asending to False.

In [22]:
sql.rename(columns ={'Destination':'destination'},inplace = True)

inplace = True  it means changes apply directly to original dataframe 
inplace = False it means it creates new and modifired dataframe and return it 
when inplace = True the rename() operation modifies the dataframe sql directly . The original function is permanently changes, and the method returns None.

If you were to use inplace=False (False is default) , the rename() method would return a new DataFrame with the renamed column , while lwaving the original dataframe unchanged .You would typically assign this new dataframe to a variable , like new_df = df.rename()

In [23]:
sql.head()

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5

In [24]:
sql.groupby('occupation').size().to_frame('Count').reset_index()

                                   occupation  Count
0                  Architecture & Engineering    175
1    Arts Design Entertainment Sports & Media    629
2   Building & Grounds Cleaning & Maintenance     44
3                        Business & Financial    544
4                 Community & Social Services    241
5                     Computer & Mathematical   1408
6                   Construction & Extraction    154
7                  Education&Training&Library    943
8                  Farming Fishing & Forestry     43
9          Food Preparation & Serving Related    298
10       Healthcare Practitioners & Technical    244
11                         Healthcare Support    242
12          Installation Maintenance & Repair    133
13                                      Legal    219
14               Life Physical Social Science    170
15                                 Management    838
16            Office & Administrative Support    639
17                    Personal Care & Service    175
18                     Production Occupations    110
19                         Protective Service    175
20                                    Retired    495
21                            Sales & Related   1093
22                                    Student   1584
23           Transportation & Material Moving    218
24                                 Unemployed   1870

sql -- placeholder for pandas dataframe . A dataframe is a data structure that organizes data into 2D table of rows and columns,similar to a spreadsheet.

.groupby('occupation') -- this is first step in a 'split apply combine' operation 
1) the groupby() method splitsthe dataframe into smaller groups based on unique values in the specified column.
2) In this case, it groups all rows that have the same'occupation' together.

.size() -- This is an aggregation method applied to the grouped object.
1) size() -- counts the number of rows (or elements) in each group.It is similar to.
2) count() -- but it includes missing values(NaN) and works on the entire group , not on a specific column.
3) The result of this operations is a pandas series , where the index is unique 'occupation' values and the values are the counts for each occupation.


.to_frame('Count) -- The size() method returns a Series, which can sometimes be difficult to work with
for further operations.
The .to_frame() method converts this Series into a DataFrame.
'Count' is an optional argument that names the new column containing the
counts. Without this argument, the column would be given a default name (like 0
or size ).

.reset_index()
After a groupby() operation, the grouped column ('occupation' in this case)
becomes the index of the resulting Series or DataFrame.
The reset_index() method converts this index back into a regular column, so

that 'occupation' is no longer the index and the DataFrame has a default integer-
based index (starting from 0).

Overall, the code performs the following task:
It counts the number of occurrences of each unique value in the 'occupation'
column of a DataFrame. The final result is a new DataFrame with two columns:
'occupation' and 'Count', which shows the count of each occupation.
This is a very common pattern in data analysis to get a frequency count of categorical
data.

This is a very common pattern in data analysis to get a frequency count of categorical
data.

In [36]:
sql.groupby('weather')['temperature'].mean().to_frame('avg_temp').reset_index()

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

In [37]:
sql.groupby('weather')['temperature'].size().to_frame('count_temp').reset_index()

  weather  count_temp
0   Rainy        1210
1   Snowy        1405
2   Sunny       10069

['temperature'].size() ['temperature'] selects the 'temperature' column from each of the groups created in the previous step.

.size() is an aggregation method. It counts the number of rows (or elements) within each
group. The result is a Pandas Series where the index is the unique 'weather' values and
the values are the counts for each weather type.

In [38]:
sql.groupby('weather')['temperature'].nunique().to_frame('count_distinct_temp')

         count_distinct_temp
weather
Rainy                      1
Snowy                      1
Sunny                      3

In [39]:
sql.groupby('weather')['temperature'].min().to_frame('min_temp').reset_index()

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        30

In [40]:
sql.groupby('occupation').filter(lambda x : x['occupation'].iloc[0] == 'Student').groupby('occupation').size()

occupation
Student    1584
dtype: int64

What the code does (high level)

It finds every row whose occupation is Student and then counts how many such rows there are. The result is a Series like occupation -> count (usually just one entry: Student: N).

sql.groupby('occupation')

Group the DataFrame sql by the occupation column. Internally you now have one small DataFrame (x) per occupation (e.g. one group for "Student", one for "Teacher", etc.).

.filter(lambda x: x['occupation'].iloc[0] == 'Student')

filter runs the lambda for each group x.

x['occupation'].iloc[0] takes the occupation value from the first row of that group. (Because each group was made by occupation, that value will be the same for the whole group.)

The lambda returns True only for the group whose occupation is 'Student'. filter then returns a new DataFrame containing all rows from groups where the lambda was True — i.e., all rows with occupation == 'Student'.

.groupby('occupation').size()

Now group that filtered DataFrame by occupation again (but it only contains the Student rows).

.size() computes the number of rows in each group. Since only the Student group remains, you get a Series like:

In summary, the code effectively counts the total number of rows where the
'occupation' is 'Student' .

In [41]:
sql1 = pd.read_csv(r"E:\FSDS\Dataset\vehicle_coupon.csv")

In [43]:
pd.concat([sql,sql1]) ['temperature'].drop_duplicates

<bound method Series.drop_duplicates of 0        55
1        80
2        80
3        80
4        80
         ..
12679    55
12680    55
12681    30
12682    30
12683    80
Name: temperature, Length: 25368, dtype: int64>

pd.concat([sql, sql1])

Joins the two DataFrames vertically (one below the other).

Default is axis=0, so rows from sql come first, then rows from sql1.

Columns are merged (if one DF is missing a column you get NaN for those rows).

The resulting object is a DataFrame. Index values from both inputs are preserved (so you may get duplicate indexes).

['temperature']

Selects the temperature column from that concatenated DataFrame.

This returns a Series containing all temperature values (in the order: all from sql, then all from sql1).

.drop_duplicates()

Removes duplicate values in that Series, keeping the first occurrence of each value (default keep='first').

Returns a Series of unique temperature values in the order they first appeared. The original index labels are kept (so the index may look non-sequential or contain duplicates).

Note: if there are NaN values, drop_duplicates() will keep one NaN (it treats additional NaNs as duplicates).

Summary
In essence, the entire command can be summarized as:
"Take the two dataframes, sql and sql1 , combine them into one. Then, from this new
combined dataframe, select the destination column. Finally, remove all duplicate
entries from that column, giving me a clean list of all unique destinations from both
original dataframes."

In [46]:
sql[sql['passanger'] == 'Alone'][['Destination','passanger']]

           Destination passanger
0      No Urgent Place     Alone
13                Home     Alone
14                Home     Alone
15                Home     Alone
16                Work     Alone
...                ...       ...
12676             Home     Alone
12680             Work     Alone
12681             Work     Alone
12682             Work     Alone
12683             Work     Alone

[7305 rows x 2 columns]

"From the sql DataFrame, show me only the Destination and passanger columns for all
the rows where the value in the passanger column is 'Alone'

In [48]:
sql[sql['weather'].str.startswith('Sun')]

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12673,Home,Alone,Sunny,30,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,0,12674
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

"From the sql DataFrame, select and return all rows where the text in the weather column
starts with 'Sun'.

In [50]:
sql[(sql['temperature']>=29) & (sql['temperature']>=75)] ['temperature'].unique()

array([80])

his is a method called on the Series of temperature values.
It returns an array of all the unique values present in that Series, removing any duplicates.
Final Output: A NumPy array containing a list of all the distinct temperature values that
were 75 or greater.

In [54]:
sql[sql['occupation'].isin(['Sales & Related','Management'])][['occupation']]

            occupation
193    Sales & Related
194    Sales & Related
195    Sales & Related
196    Sales & Related
197    Sales & Related
...                ...
12679  Sales & Related
12680  Sales & Related
12681  Sales & Related
12682  Sales & Related
12683  Sales & Related

[1931 rows x 1 columns]

What it does (short)

It selects only the rows where occupation is either "Sales & Related" or "Management", and then returns a DataFrame that contains only the occupation column for those rows.

Step-by-step (simple)

sql['occupation'].isin(['Sales & Related','Management'])

Builds a boolean mask (a Series of True/False).

Each row is True if that row’s occupation value is one of the two items in the list, otherwise False.

sql[ ... ]

Uses that boolean mask to filter rows of sql. Only rows where the mask is True are kept.

[['occupation']]

After filtering, this selects the occupation column as a DataFrame (double brackets).

If you used single brackets ['occupation'] you would get a Series instead.